population:
  pop-size:
    short: -p
    type: int
    default: 20000
    help: 'Number of genomes in the population (default: 20000)'
  generations:
    short: -g
    type: int
    default: 300
    help: 'Number of generations to run (default: 300)'
  elite-frac:
    short: -e
    type: float
    default: 0.1
    help: 'Fraction of population to keep as elite (default: 0.1)'
  tourney-k:
    short: -k
    type: int
    default: 3
    help: 'Number of genomes to select for tournament (default: 3)'

mutation:
  mut-rule:
    short: -r
    type: float
    default: 0.03
    help: 'Probability of mutating each rule entry (default: 0.03)'
  mut-prog:
    short: -m
    type: float
    default: 0.08
    help: 'Probability of mutating each program cell (default: 0.08)'
  prog-len:
    short: -l
    type: int
    default: 10
    help: 'Length of the program sequence (default: 10)'

regularization:
  lambda-p:
    short: -a
    type: float
    default: 0.01
    help: 'Sparsity penalty coefficient (default: 0.01)'
  random-immigrants:
    short: -i
    type: float
    default: 0.2
    help: 'Probability of introducing random immigrants (default: 0.2)'
  complex-telemetry:
    short: -c
    type: int
    default: 30
    help: 'Frequency of detailed telemetry (in generations) (default: 30)'

simulation:
  window:
    short: -w
    type: int
    default: 200
    help: 'Tape length for simulation (default: 200)'
  max-steps:
    short: -s
    type: int
    default: 800
    help: 'Maximum simulation steps (default: 800)'
  halt-thresh:
    short: -t
    type: float
    default: 0.50
    help: 'Threshold for early stopping (default: 0.50)'

checkpoint:
  check-every:
    short: -f
    type: int
    default: 50
    help: 'Frequency of checkpoint saving (default: 50)'
  save-dir:
    short: -d
    type: str
    default: dp_checkpoints
    help: 'Directory for checkpoints (default: dp_checkpoints)'

input-output:
  input-set:
    short: -x
    type: str
    default: 'np.arange(1, 31)'
    help: 'Input range expression (e.g. "np.arange(1, 31)")'
  target-out:
    short: -y
    type: str
    default: 'np.arange(1, 31) * 2'
    help: 'Target output expression (e.g. "np.arange(1, 31) * 2")'

# Default configuration file path
config_file: config.yaml
